# Generated by Django 5.1.3 on 2024-11-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
